### ISSUE TITLE
Cannot find module rnplugin../makepods.js

### ISSUE THREAD

**Issue by loic-lopez** [rhdeck/react-native-pod#4]
See:
```
/node_modules/react-native-pod/rnplugin../makepods.js'
Error: Cannot find module 'node_modules/react-native-pod/rnplugin../makepods.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.module.exports [as func] (node_modules/react-native-pod/rnplugin/installpods.js:6:5)
    at Promise.resolve.then (node_modules/react-native/local-cli/cliEntry.js:117:22)

```

**Comment by rhdeck** [comment]
Fixed `installpods` command
